version: 0.2

phases:
  pre_build:
    commands:
      - composer install 

  build:
    commands:
      - './vendor/bin/phpunit --bootstrap ./vendor/autoload.php ./**/*.spec.php'

artifacts:
  files:
    - '**/*'
